# Change these first
owner: higgco # Your GitHub organization or username, where this repository lives
repo: higg-status # The name of this repository

sites:
  - name: Portal HIGG
    url: https://portal.higg.org
  - name: Portal HIGG Backend
    url: $API_URL
    method: GET
  - name: Profiles HIGG
    url: https://profiles.higg.com
  - name: Corp Reporting
    url: https://corpreporting.higg.com
  - name: App Worldly
    url: https://worldly.io
  - name: Learn Worldly
    url: https://learn.worldly.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.worldly.io
  #baseUrl: /upptime-test
  logoUrl: https://higg.com/wp-content/uploads/2021/10/higg_lockup-TrustedSustainabilityData_Black_200px.png
  name: Worldly Status Page
  introTitle: "**Higg** is an integrated software platform that helps you take responsibility for your business's environmental and social impact."
  introMessage: Status Page
  navbar:
    - title: Status
      href: /

i18n:
  footer: For more information visit our [web page](https://worldly.io)
  
workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  summary: "0 * * * *"
  updates: "0 * * * *"
  uptime: "*/10 * * * *"
