# Change these first
owner: higgco # Your GitHub organization or username, where this repository lives
repo: higg-status # The name of this repository.

sites:
  - name: worldly.io
    url: https://worldly.io
  - name: Worldly Backend
    url: https://api-v2.production.higg.org/tou/fem
    method: GET
  - name: Learn Worldly
    url: https://learn.worldly.io
  - name: Profiles HIGG
    url: https://profiles.higg.com
  - name: Corp Reporting
    url: https://corpreporting.higg.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.worldly.io
  customHeadHtml: |
    <div id="updateCard" class="update-card">
      Last Update: <span id="last-update">2025-12-27 22:02 UTC</span>
    </div>
  #baseUrl: /upptime-test
  logoUrl: https://worldly.io/wp-content/uploads/2023/04/Worldly_LogoTM_Urgency@4x-200x50.png
  name: Worldly Status Page
  introTitle: "**Worldly** is an integrated software platform that helps you take responsibility for your business's environmental and social impact."
  introMessage: Status Page
  navbar:
    - title: Status
      href: /

  links:
    - rel: stylesheet
      href: /assets/custom-styles.css

i18n:
  footer: For more information visit our [web page](https://worldly.io)
  
workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  summary: "0 * * * *"
  updates: "0 * * * *"
  uptime: "*/10 * * * *"
version: latest
